spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_board
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000


  security:
    user:
      name: a
      password: a


  profiles:
    active: local
    include: jwt

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jwt:
    secret: e2aeedff8aa5902e2e5a7f40ec6343f2c3d168359ed4b10420a3a5b72296836c


  mvc:
    static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework: INFO # 로그인, 상태변경 같은 정보성 메세지
    org.springframework.web: DEBUG


