spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_board
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  security:
    user:
      name: a
      password: a


  profiles:
    active: local
    include: jwt

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jwt:
    secret: e2aeedff8aa5902e2e5a7f40ec6343f2c3d168359ed4b10420a3a5b72296836c

  cache:
    cache-names: "cache1,cache2"
    caffeine:
      spec: "maximumSize=500, expireAfterAccess=600s"

  data:
    redis:
      host: localhost
      port: 8090
      timeout: 6

logging:
  level:
    root: debug

